#include "render.h"
#include "audio.h"
#include <stdio.h>
#include <string.h>
#include <math.h>

// --- Embedded king sprites (generated by xxd -i) ---
#include "king_idle_state.h"
#include "king_angry_state.h"
#include "king_overwhelmed_state.h"
#include "king_turned_head.h"
#include "wanderer_hooded.h"
#include "wanderer_idle.h"
#include "lesb_final.h"
#include "princess.h"

// --- Embedded table sprite (generated by xxd -i) ---
#include "table_sprite.h"

static Texture2D g_king_idle;
static Texture2D g_king_angry;
static Texture2D g_king_overwhelmed;
static Texture2D g_king_turned;
static bool g_king_sprites_loaded = false;

static Texture2D g_wanderer_hooded;
static Texture2D g_wanderer_idle;
static bool g_wanderer_loaded = false;

static Texture2D g_final_tex;
static bool g_final_loaded = false;

static Texture2D g_princess_tex;
static bool g_princess_loaded = false;

static Texture2D g_table_texture;
static bool g_table_loaded = false;

static Font g_font;
static bool g_font_loaded = false;

static Font g_font_sym;        // Segoe UI Symbol — for ♠♣♥♦ glyphs
static bool g_font_sym_loaded = false;

static float g_uiBlock = 0;

// --- Royal UI palette ---
#define ROYAL_GOLD      GOLD
#define ROYAL_GOLD_DIM  (Color){ 146, 116, 63, 220 }

static Color ScaleColor(Color c, float k) {
    Color r = c;
    r.r = (unsigned char)(c.r * k > 255.0f ? 255 : c.r * k);
    r.g = (unsigned char)(c.g * k > 255.0f ? 255 : c.g * k);
    r.b = (unsigned char)(c.b * k > 255.0f ? 255 : c.b * k);
    return r;
}

void DrawDiamond(Vector2 c, float r, Color col) {    Rectangle sq = { c.x - r, c.y - r, r * 2.0f, r * 2.0f };
    Vector2 tl = { sq.x, sq.y };
    Vector2 tr = { sq.x + sq.width, sq.y };
    Vector2 bl = { sq.x, sq.y + sq.height };
    Vector2 br = { sq.x + sq.width, sq.y + sq.height };
    DrawTriangle(tl, bl, tr, col);
    DrawTriangle(tr, bl, br, col);
}

void DrawRoyalPanel(Rectangle rect, Color accent) {
    const float rnd = 0.10f;
    int seg = 12;

    Rectangle sh = { rect.x + 4, rect.y + 6, rect.width, rect.height };
    DrawRectangleRounded(sh, rnd, seg, (Color){0, 0, 0, 120});

    DrawRectangleRounded(rect, rnd, seg, ROYAL_PANEL_BG);

    float cap = rect.height * 0.12f;
    if (cap > 14.0f) cap = 14.0f;
    if (cap > 4.0f) {
        Rectangle sheen = { rect.x + 10, rect.y + 4, rect.width - 20, cap };
        DrawRectangleRounded(sheen, 0.35f, 8, (Color){255, 240, 200, 16});
        Rectangle shade = { rect.x + 10, rect.y + rect.height - 4 - cap * 0.7f, rect.width - 20, cap * 0.7f };
        DrawRectangleRounded(shade, 0.35f, 8, (Color){0, 0, 0, 45});
    }

    DrawRectangleRoundedLines(rect, rnd, seg, accent);
    Rectangle b2 = { rect.x + 3, rect.y + 3, rect.width - 6, rect.height - 6 };
    DrawRectangleRoundedLines(b2, rnd, seg, Fade(accent, 0.40f));

    float m = 9.0f;
    if (rect.width > m * 6 && rect.height > m * 6) {
        Vector2 corners[4] = {
            { rect.x + m, rect.y + m },
            { rect.x + rect.width - m, rect.y + m },
            { rect.x + m, rect.y + rect.height - m },
            { rect.x + rect.width - m, rect.y + rect.height - m }
        };
        for (int i = 0; i < 4; i++) {
            DrawDiamond(corners[i], 3.6f, accent);
            DrawDiamond(corners[i], 1.6f, ScaleColor(accent, 1.5f));
        }
    }
}

void BlockUiClicks(float seconds) { if (seconds > g_uiBlock) g_uiBlock = seconds; }
void UpdateUiBlock(float dt) { if (g_uiBlock > 0) { g_uiBlock -= dt; if (g_uiBlock < 0) g_uiBlock = 0; } }

void DrawPaperPanel(Rectangle rect) {
    // soft drop shadow
    Rectangle sh = { rect.x + 5, rect.y + 8, rect.width, rect.height };
    DrawRectangleRounded(sh, 0.07f, 12, (Color){0, 0, 0, 85});
    // parchment base with subtle gradient
    DrawRectangleRounded(rect, 0.07f, 12, (Color){250, 240, 220, 255});
    Rectangle innerBg = { rect.x + 6, rect.y + 6, rect.width - 12, rect.height - 12 };
    DrawRectangleRounded(innerBg, 0.06f, 10, (Color){245, 232, 205, 255});
    // double ornate border
    DrawRectangleRoundedLines(rect, 0.07f, 12, (Color){165, 145, 110, 255});
    DrawRectangleRoundedLines(innerBg, 0.06f, 10, (Color){195, 175, 135, 200});
    // corner rosettes
    float cr = 7.0f;
    Vector2 corners[4] = {
        {rect.x + 18, rect.y + 18}, {rect.x + rect.width - 18, rect.y + 18},
        {rect.x + 18, rect.y + rect.height - 18}, {rect.x + rect.width - 18, rect.y + rect.height - 18}
    };
    for (int i = 0; i < 4; i++) {
        DrawCircleV(corners[i], cr, (Color){180, 160, 120, 255});
        DrawCircleV(corners[i], cr*0.55f, (Color){245, 235, 210, 255});
        DrawCircleV(corners[i], 2.0f, (Color){165, 145, 110, 255});
    }
    // wax seal bottom-right
    Vector2 seal = { rect.x + rect.width - 46, rect.y + rect.height - 46 };
    DrawCircleV(seal, 18, (Color){165, 45, 45, 255});
    DrawCircleV(seal, 15, (Color){185, 60, 60, 255});
    DrawCircleLines((int)seal.x, (int)seal.y, 15, (Color){120, 30, 30, 180});
    DrawCircleLines((int)seal.x, (int)seal.y, 18, (Color){90, 20, 20, 120});
    // subtle horizontal ruling
    for (int i = 0; i < 2; i++) {
        float y = rect.y + rect.height*0.32f + i * 18;
        DrawLineEx((Vector2){rect.x + 22, y}, (Vector2){rect.x + rect.width*0.62f, y}, 1.0f, Fade((Color){180,160,120,255}, 0.07f));
    }
}

void DrawTitleFlourish(Vector2 center, float width, Color accent) {
    float half = width * 0.5f;
    float gap = 12.0f;
    DrawLineEx((Vector2){center.x - half, center.y}, (Vector2){center.x - gap, center.y}, 2.0f, Fade(accent, 0.75f));
    DrawLineEx((Vector2){center.x + gap, center.y}, (Vector2){center.x + half, center.y}, 2.0f, Fade(accent, 0.75f));
    DrawLineEx((Vector2){center.x - half + 5, center.y + 4}, (Vector2){center.x - gap - 8, center.y + 4}, 1.0f, Fade(accent, 0.35f));
    DrawLineEx((Vector2){center.x + gap + 8, center.y + 4}, (Vector2){center.x + half - 5, center.y + 4}, 1.0f, Fade(accent, 0.35f));
    DrawDiamond(center, 4.5f, accent);
    DrawDiamond((Vector2){center.x - half, center.y}, 2.5f, Fade(accent, 0.85f));
    DrawDiamond((Vector2){center.x + half, center.y}, 2.5f, Fade(accent, 0.85f));
}

void InitKingSprites(void) {
    Image img;

    img = LoadImageFromMemory(".png",
        src_characters_king_idle_state_png,
        (int)src_characters_king_idle_state_png_len);
    g_king_idle = LoadTextureFromImage(img);
    SetTextureFilter(g_king_idle, TEXTURE_FILTER_BILINEAR);
    UnloadImage(img);

    img = LoadImageFromMemory(".png",
        src_characters_king_angry_state_png,
        (int)src_characters_king_angry_state_png_len);
    g_king_angry = LoadTextureFromImage(img);
    SetTextureFilter(g_king_angry, TEXTURE_FILTER_BILINEAR);
    UnloadImage(img);

    img = LoadImageFromMemory(".png",
        src_characters_king_overwhelmed_state_png,
        (int)src_characters_king_overwhelmed_state_png_len);
    g_king_overwhelmed = LoadTextureFromImage(img);
    SetTextureFilter(g_king_overwhelmed, TEXTURE_FILTER_BILINEAR);
    UnloadImage(img);

    img = LoadImageFromMemory(".png",
        src_characters_king_turned_head_png,
        (int)src_characters_king_turned_head_png_len);
    g_king_turned = LoadTextureFromImage(img);
    SetTextureFilter(g_king_turned, TEXTURE_FILTER_BILINEAR);
    UnloadImage(img);

    g_king_sprites_loaded = true;
}

void InitWandererSprites(void) {
    Image img = LoadImageFromMemory(".png",
        src_characters_wanderer_hooded_png,
        (int)src_characters_wanderer_hooded_png_len);
    g_wanderer_hooded = LoadTextureFromImage(img);
    SetTextureFilter(g_wanderer_hooded, TEXTURE_FILTER_BILINEAR);
    UnloadImage(img);
    img = LoadImageFromMemory(".png",
        src_characters_wanderer_idle_png,
        (int)src_characters_wanderer_idle_png_len);
    g_wanderer_idle = LoadTextureFromImage(img);
    SetTextureFilter(g_wanderer_idle, TEXTURE_FILTER_BILINEAR);
    UnloadImage(img);
    g_wanderer_loaded = true;
}

void UnloadWandererSprites(void) {
    if (g_wanderer_loaded) {
        UnloadTexture(g_wanderer_hooded);
        UnloadTexture(g_wanderer_idle);
        g_wanderer_loaded = false;
    }
}

void DrawWanderer(Rectangle rect, Color tint) {
    // Default hooded variant
    DrawWandererEx(rect, true, tint);
}

void InitFinalSprite(void) {
    Image img = LoadImageFromMemory(".png",
        src_characters_lesb_final_png,
        (int)src_characters_lesb_final_png_len);
    g_final_tex = LoadTextureFromImage(img);
    SetTextureFilter(g_final_tex, TEXTURE_FILTER_BILINEAR);
    UnloadImage(img);
    g_final_loaded = true;
}

void UnloadFinalSprite(void) {
    if (g_final_loaded) {
        UnloadTexture(g_final_tex);
        g_final_loaded = false;
    }
}

void DrawFinalImage(Rectangle dst, float alpha) {
    if (!g_final_loaded) return;
    Color tint = Fade(WHITE, alpha);
    Rectangle src = { 0, 0, (float)g_final_tex.width, (float)g_final_tex.height };
    DrawTexturePro(g_final_tex, src, dst, (Vector2){0,0}, 0.0f, tint);
}

void DrawFinalImageCentered(int screenWidth, int screenHeight, float alpha) {
    if (!g_final_loaded) return;
    float texW = (float)g_final_tex.width;
    float texH = (float)g_final_tex.height;
    float maxW = screenWidth * 0.46f; // left half
    float maxH = screenHeight * 0.82f;
    float scale = fminf(maxW / texW, maxH / texH);
    float w = texW * scale;
    float h = texH * scale;
    // Editable: bottomOffset and leftMargin to move image
    float bottomOffset = 0.0f; // 0 = touches bottom
    float leftMargin = 42.0f;  // <-- change to move left/right
    Rectangle dst = { leftMargin, screenHeight - h - bottomOffset, w, h };
    DrawFinalImage(dst, alpha);
}

void InitPrincessSprite(void) {
    Image img = LoadImageFromMemory(".png",
        src_characters_princess_png,
        (int)src_characters_princess_png_len);
    g_princess_tex = LoadTextureFromImage(img);
    SetTextureFilter(g_princess_tex, TEXTURE_FILTER_BILINEAR);
    UnloadImage(img);
    g_princess_loaded = true;
}

void UnloadPrincessSprite(void) {
    if (g_princess_loaded) {
        UnloadTexture(g_princess_tex);
        g_princess_loaded = false;
    }
}

void DrawPrincess(Rectangle rect, Color tint) {
    if (!g_princess_loaded) return;
    Texture2D tex = g_princess_tex;
    float srcW = (float)tex.width;
    float srcH = (float)tex.height;
    float scaleX = rect.width / srcW;
    float scaleY = rect.height / srcH;
    float scale = (scaleX < scaleY) ? scaleX : scaleY;
    float dstW = srcW * scale;
    float dstH = srcH * scale;
    float dstX = rect.x + (rect.width - dstW) * 0.5f;
    float dstY = rect.y + (rect.height - dstH) * 0.5f;
    Rectangle srcRect = { 0, 0, srcW, srcH };
    Rectangle dstRect = { dstX, dstY, dstW, dstH };
    DrawTexturePro(tex, srcRect, dstRect, (Vector2){0,0}, 0.0f, tint);
}

void DrawHeart(Vector2 center, float size, Color col) {
    DrawSuitSymbol(center, size, SUIT_HEARTS, col);
}

void DrawWandererEx(Rectangle rect, bool hooded, Color tint) {
    if (!g_wanderer_loaded) return;
    Texture2D tex = hooded ? g_wanderer_hooded : g_wanderer_idle;
    float srcW = (float)tex.width;
    float srcH = (float)tex.height;
    float scaleX = rect.width / srcW;
    float scaleY = rect.height / srcH;
    float scale = (scaleX < scaleY) ? scaleX : scaleY;
    float characterScale = 4.0f;
    scale *= characterScale;
    float dstW = srcW * scale;
    float dstH = srcH * scale;
    float dstX = rect.x + (rect.width - dstW) * 0.5f;
    float dstY = rect.y + (rect.height - dstH) * 0.5f;
    Rectangle srcRect = { 0, 0, srcW, srcH };
    Rectangle dstRect = { dstX, dstY, dstW, dstH };
    DrawTexturePro(tex, srcRect, dstRect, (Vector2){0, 0}, 0.0f, tint);
}

void DrawWandererRevealEffect(Rectangle rect, float progress) {
    if (progress < 0) progress = 0;
    if (progress > 1) progress = 1;
    Vector2 center = { rect.x + rect.width * 0.5f, rect.y + rect.height * 0.35f };
    // Expanding golden ring
    float ringR = 25.0f + progress * 110.0f;
    DrawCircleLines((int)center.x, (int)center.y, ringR, Fade(GOLD, 0.55f * (1.0f - progress)));
    DrawCircleLines((int)center.x, (int)center.y, ringR * 0.72f, Fade(WHITE, 0.35f * (1.0f - progress)));
    // Soft flash disc
    DrawCircleV(center, 18.0f + progress * 45.0f, Fade((Color){255, 240, 180, 255}, 0.28f * (1.0f - progress)));
    // Golden dust sparkles
    for (int i = 0; i < 14; i++) {
        float a = (i * 137.5f) * DEG2RAD + progress * 1.2f;
        float d = 12.0f + (i % 4) * 18.0f + progress * 35.0f;
        float sz = 2.2f + (i % 3) * 1.1f;
        Vector2 p = { center.x + cosf(a) * d, center.y + sinf(a) * d * 0.72f };
        DrawCircleV(p, sz * (1.0f - progress * 0.5f), Fade(GOLD, 0.85f * (1.0f - progress)));
        DrawCircleV((Vector2){p.x, p.y - 1}, sz * 0.5f, Fade(WHITE, 0.9f * (1.0f - progress)));
    }
}

float EaseOutCubic(float t) {
    float u = 1 - t;
    return 1 - u*u*u;
}
float EaseOutBack(float t) {
    float c1 = 1.70158f;
    float c3 = c1 + 1;
    return 1 + c3 * powf(t - 1, 3) + c1 * powf(t - 1, 2);
}
// --- Victory gold dust ---
#define MAX_VICTORY_PARTICLES 64
typedef struct { Vector2 pos, vel; float life, maxLife; float size; float spin; Color col; } VictoryParticle;
static VictoryParticle g_vp[MAX_VICTORY_PARTICLES];
void SpawnVictoryParticles(Vector2 origin) {
    for (int i=0;i<MAX_VICTORY_PARTICLES;i++) {
        float a = GetRandomValue(0,360) * DEG2RAD;
        float sp = GetRandomValue(60, 220);
        float sz = GetRandomValue(2, 6);
        g_vp[i].pos = (Vector2){ origin.x + GetRandomValue(-12,12), origin.y + GetRandomValue(-10,10) };
        g_vp[i].vel = (Vector2){ cosf(a)*sp, sinf(a)*sp - GetRandomValue(20,60) };
        g_vp[i].life = 0;
        g_vp[i].maxLife = GetRandomValue(700, 1300)/1000.0f;
        g_vp[i].size = sz;
        g_vp[i].spin = GetRandomValue(0, 628)/100.0f;
        int pick = GetRandomValue(0,2);
        g_vp[i].col = pick==0 ? GOLD : pick==1 ? (Color){255, 215, 140, 255} : (Color){255, 240, 180, 255};
    }
    for (int i=0;i<MAX_VICTORY_PARTICLES;i++) g_vp[i].life = g_vp[i].maxLife * (0.6f + GetRandomValue(0,40)/100.0f);
}
void UpdateVictoryParticles(float dt) {
    for (int i=0;i<MAX_VICTORY_PARTICLES;i++) if (g_vp[i].life > 0) {
        g_vp[i].life -= dt;
        g_vp[i].pos.x += g_vp[i].vel.x * dt;
        g_vp[i].pos.y += g_vp[i].vel.y * dt;
        g_vp[i].vel.y += 180.0f * dt;
        g_vp[i].vel.x *= 1.0f - 0.8f*dt;
        g_vp[i].spin += dt * GetRandomValue(3, 7);
    }
}
void DrawVictoryParticles(void) {
    for (int i=0;i<MAX_VICTORY_PARTICLES;i++) if (g_vp[i].life > 0) {
        float a = g_vp[i].life / g_vp[i].maxLife;
        float s = g_vp[i].size * (0.7f + 0.6f*a);
        Color c = Fade(g_vp[i].col, a*0.95f);
        Vector2 p = g_vp[i].pos;
        // diamond sparkle
        DrawDiamond(p, s, c);
        DrawCircleV(p, s*0.45f, Fade(WHITE, a*0.55f));
    }
}
#define MAX_CURSOR_PARTICLES 80
typedef struct { Vector2 pos, vel; float life, maxLife; float size; } CursorParticle;
static CursorParticle g_cdust[MAX_CURSOR_PARTICLES];
void SpawnCursorDust(Vector2 pos) {
    for (int k=0;k<2;k++) {
        for (int i=0;i<MAX_CURSOR_PARTICLES;i++) if (g_cdust[i].life <= 0) {
            g_cdust[i].pos = (Vector2){ pos.x + GetRandomValue(-4,4), pos.y + GetRandomValue(-4,4) };
            g_cdust[i].vel = (Vector2){ GetRandomValue(-12,12)/10.0f, GetRandomValue(-18, -6)/10.0f };
            g_cdust[i].life = g_cdust[i].maxLife = GetRandomValue(400, 750)/1000.0f;
            g_cdust[i].size = GetRandomValue(14, 26)/10.0f;
            break;
        }
    }
}
void UpdateCursorParticles(float dt) {
    for (int i=0;i<MAX_CURSOR_PARTICLES;i++) if (g_cdust[i].life > 0) {
        g_cdust[i].life -= dt;
        g_cdust[i].pos.x += g_cdust[i].vel.x * dt * 18.0f + sinf(g_cdust[i].life*4 + i)*6.0f*dt;
        g_cdust[i].pos.y += g_cdust[i].vel.y * dt * 22.0f;
        g_cdust[i].vel.y += 14.0f*dt;
        g_cdust[i].vel.x *= 1.0f - 0.9f*dt;
    }
}
void DrawCursorParticles(void) {
    for (int i=0;i<MAX_CURSOR_PARTICLES;i++) if (g_cdust[i].life > 0) {
        float a = g_cdust[i].life / g_cdust[i].maxLife;
        float s = g_cdust[i].size * (0.8f + 0.4f*a);
        Color c = Fade(GOLD, a*0.9f);
        DrawDiamond(g_cdust[i].pos, s, c);
        DrawCircleV(g_cdust[i].pos, s*0.4f, Fade((Color){255,240,180,255}, a*0.6f));
    }
}

void UnloadKingSprites(void) {
    if (g_king_sprites_loaded) {
        UnloadTexture(g_king_idle);
        UnloadTexture(g_king_angry);
        UnloadTexture(g_king_overwhelmed);
        UnloadTexture(g_king_turned);
        g_king_sprites_loaded = false;
    }
}

void InitTableSprite(void) {
    Image img = LoadImageFromMemory(".png",
        src_sprites_table_png,
        (int)src_sprites_table_png_len);
    g_table_texture = LoadTextureFromImage(img);
    SetTextureFilter(g_table_texture, TEXTURE_FILTER_BILINEAR);
    UnloadImage(img);
    g_table_loaded = true;
}

void UnloadTableSprite(void) {
    if (g_table_loaded) {
        UnloadTexture(g_table_texture);
        g_table_loaded = false;
    }
}

void InitRenderFont(void) {
    int codepoints[3000];
    int count = 0;
    
    // ASCII
    for (int i = 32; i <= 126; i++) codepoints[count++] = i;
    // Cyrillic
    for (int i = 0x0400; i <= 0x04FF; i++) codepoints[count++] = i;
    // Suit symbols (needed for fallback / symbol font)
    codepoints[count++] = 0x2660; // ♠
    codepoints[count++] = 0x2663; // ♣
    codepoints[count++] = 0x2665; // ♥
    codepoints[count++] = 0x2666; // ♦
    codepoints[count++] = 0x2794; // ➔ (Heavy Wide-Headed Rightwards Arrow)
    codepoints[count++] = 0x2192;
    // Dashes (used in UI texts)
    codepoints[count++] = 0x2013; // – en dash
    codepoints[count++] = 0x2014; // — em dash
    // --- Main text font (serif, no suit symbols) ---
    const char* fontPaths[] = {
        "C:\\Windows\\Fonts\\georgia.ttf",   // Royal Serif
        "C:\\Windows\\Fonts\\cambria.ttf",   // Royal Serif
        "C:\\Windows\\Fonts\\pala.ttf",      // Palatino Linotype
        "C:\\Windows\\Fonts\\segoeui.ttf",   // Segoe UI
        "C:\\Windows\\Fonts\\arial.ttf"      // Arial
    };

    for (int i = 0; i < 5; i++) {
        if (FileExists(fontPaths[i])) {
            g_font = LoadFontEx(fontPaths[i], 32, codepoints, count);
            if (g_font.texture.id > 0) {
                g_font_loaded = true;
                SetTextureFilter(g_font.texture, TEXTURE_FILTER_BILINEAR);
                break;
            }
        }
    }

    // --- Symbol font for glyphs missing from serif fonts (Segoe UI Symbol) ---
    int symCodepoints[] = { 0x2660, 0x2663, 0x2665, 0x2666, 0x2794, 0x2192 };
    const char* symFontPath = "C:\\Windows\\Fonts\\seguisym.ttf";
    if (FileExists(symFontPath)) {
        g_font_sym = LoadFontEx(symFontPath, 32, symCodepoints, 6);
        if (g_font_sym.texture.id > 0) {
            g_font_sym_loaded = true;
            SetTextureFilter(g_font_sym.texture, TEXTURE_FILTER_BILINEAR);
        }
    }
}

static bool IsSymbolCodepoint(int cp) {
    return (cp == 0x2660 || cp == 0x2663 || cp == 0x2665 || cp == 0x2666 ||
            cp == 0x2794 || cp == 0x2192);
}

void UnloadRenderFont(void) {
    if (g_font_loaded) {
        UnloadFont(g_font);
        g_font_loaded = false;
    }
    if (g_font_sym_loaded) {
        UnloadFont(g_font_sym);
        g_font_sym_loaded = false;
    }
}

Font GetAppFont(void) {
    if (g_font_loaded) return g_font;
    return GetFontDefault();
}

// Draw a single UTF-8 codepoint using the appropriate font (sym font for suits & arrows)
// Returns the x advance for the glyph.
static float DrawAppCodepoint(int codepoint, float x, float y, float fontSize, Color color) {
    Font fnt = (IsSymbolCodepoint(codepoint) && g_font_sym_loaded) ? g_font_sym
             : (g_font_loaded ? g_font : GetFontDefault());

    // Scale factor relative to the font's base size (32px)
    float scale = fontSize / fnt.baseSize;

    GlyphInfo gi = GetGlyphInfo(fnt, codepoint);
    int idx = GetGlyphIndex(fnt, codepoint);
    if (idx < 0 || idx >= fnt.glyphCount) {
        // Unknown glyph — draw a box, advance by fontSize/2
        DrawRectangleLines((int)x, (int)y, (int)(fontSize * 0.6f), (int)fontSize, color);
        return fontSize * 0.6f + 1.0f;
    }

    Rectangle srcRec = fnt.recs[idx];
    float drawX = x + gi.offsetX * scale;
    float drawY = y + gi.offsetY * scale;
    Rectangle dstRec = { drawX, drawY, srcRec.width * scale, srcRec.height * scale };
    DrawTexturePro(fnt.texture, srcRec, dstRec, (Vector2){0, 0}, 0.0f, color);

    float advance = (gi.advanceX > 0 ? gi.advanceX : (srcRec.width + gi.offsetX)) * scale + 1.0f;
    return advance;
}

void DrawAppText(const char* text, float posX, float posY, float fontSize, Color color) {
    if (!text || text[0] == '\0') return;

    float x = posX;
    float y = posY;
    float lineHeight = fontSize * 1.2f; // line spacing
    int i = 0;
    while (text[i] != '\0') {
        if (text[i] == '\n') {
            x = posX;
            y += lineHeight;
            i++;
            continue;
        }
        int cpLen = 0;
        int cp = GetCodepointNext(&text[i], &cpLen);
        if (cp == 0 || cpLen == 0) break;
        x += DrawAppCodepoint(cp, x, y, fontSize, color);
        i += cpLen;
    }
}

Vector2 MeasureAppText(const char* text, float fontSize) {
    if (!text || text[0] == '\0') return (Vector2){0, fontSize * 1.2f};

    float maxWidth = 0.0f;
    float lineWidth = 0.0f;
    int lines = 1;
    int i = 0;
    while (text[i] != '\0') {
        if (text[i] == '\n') {
            if (lineWidth > maxWidth) maxWidth = lineWidth;
            lineWidth = 0.0f;
            lines++;
            i++;
            continue;
        }
        int cpLen = 0;
        int cp = GetCodepointNext(&text[i], &cpLen);
        if (cp == 0 || cpLen == 0) break;

        bool isSym = IsSymbolCodepoint(cp);
        Font fnt = (isSym && g_font_sym_loaded) ? g_font_sym
                 : (g_font_loaded ? g_font : GetFontDefault());
        float scale = fontSize / fnt.baseSize;

        int idx = GetGlyphIndex(fnt, cp);
        float advance = 0.0f;
        if (idx >= 0 && idx < fnt.glyphCount) {
            GlyphInfo gi = fnt.glyphs[idx];
            advance = (gi.advanceX > 0 ? gi.advanceX : (fnt.recs[idx].width + gi.offsetX)) * scale + 1.0f;
        } else {
            advance = fontSize * 0.6f + 1.0f;
        }
        lineWidth += advance;
        i += cpLen;
    }
    if (lineWidth > maxWidth) maxWidth = lineWidth;
    float totalHeight = lines * (fontSize * 1.2f);
    return (Vector2){ maxWidth, totalHeight };
}


bool DrawMenuButton(Rectangle rect, const char* text, bool isHovered, Color baseColor, Color hoverColor) {
    const float rnd = 0.18f;
    int seg = 10;
    Color bg = isHovered ? hoverColor : baseColor;

    Rectangle sh = { rect.x + 3, rect.y + 5, rect.width, rect.height };
    DrawRectangleRounded(sh, rnd, seg, (Color){0, 0, 0, (unsigned char)(isHovered ? 150 : 95)});

    DrawRectangleRounded(rect, rnd, seg, bg);

    float cap = rect.height * 0.42f;
    Rectangle sheen = { rect.x + 4, rect.y + 3, rect.width - 8, cap };
    DrawRectangleRounded(sheen, 0.35f, 6, (Color){255, 255, 255, (unsigned char)(isHovered ? 26 : 12)});
    Rectangle shade = { rect.x + 4, rect.y + rect.height - cap * 0.6f - 3, rect.width - 8, cap * 0.6f };
    DrawRectangleRounded(shade, 0.35f, 6, (Color){0, 0, 0, 45});

    DrawRectangleRoundedLines(rect, rnd, seg, isHovered ? ROYAL_GOLD : ROYAL_GOLD_DIM);
    if (isHovered) {
        Rectangle gl = { rect.x - 3, rect.y - 3, rect.width + 6, rect.height + 6 };
        DrawRectangleRoundedLines(gl, rnd, seg, (Color){255, 215, 0, 70});

        Vector2 sz0 = MeasureAppText(text, 24);
        float cx = rect.x + rect.width * 0.5f;
        float cy = rect.y + rect.height * 0.5f;
        float dx = sz0.x * 0.5f + 16.0f;
        if (dx < rect.width * 0.5f - 14.0f) {
            DrawDiamond((Vector2){cx - dx, cy}, 3.2f, GOLD);
            DrawDiamond((Vector2){cx + dx, cy}, 3.2f, GOLD);
        }
    }

    float fontSize = 24;
    Vector2 sz = MeasureAppText(text, fontSize);
    float textX = rect.x + (rect.width - sz.x) / 2.0f;
    float textY = rect.y + (rect.height - sz.y) / 2.0f;
    DrawAppText(text, textX + 1.5f, textY + 2.0f, fontSize, (Color){0, 0, 0, 170});
    Color txtCol = isHovered ? ROYAL_GOLD : ROYAL_PARCHMENT;
    if (!isHovered) txtCol = ScaleColor(txtCol, 1.0f);
    DrawAppText(text, textX, textY, fontSize, txtCol);

    bool blocked = g_uiBlock > 0;
    bool clicked = !blocked && isHovered && IsMouseButtonPressed(MOUSE_LEFT_BUTTON);
    if (clicked) PlayButtonSfx();
    return clicked;
}

int DrawConfirmationModal(const char* title, const char* yesText, const char* noText, int screenWidth, int screenHeight, Vector2 mousePos) {
    // Backdrop dim
    DrawRectangle(0, 0, screenWidth, screenHeight, (Color){0, 0, 0, 180});

    // Modal Box
    float boxW = 540, boxH = 220;
    Rectangle box = {screenWidth/2.0f - boxW/2.0f, screenHeight/2.0f - boxH/2.0f, boxW, boxH};
    DrawRoyalPanel(box, ROYAL_GOLD);
    DrawTitleFlourish((Vector2){screenWidth / 2.0f, box.y + 62}, 300, ROYAL_GOLD);

    // Title text
    Vector2 titleSz = MeasureAppText(title, 26);
    DrawAppText(title, screenWidth/2.0f - titleSz.x/2.0f, box.y + 30, 26, GOLD);

    // Buttons
    float btnW = 150, btnH = 50;
    float btnY = box.y + 125;

    // YES Button
    Rectangle rYes = {screenWidth/2.0f - btnW - 20, btnY, btnW, btnH};
    bool hYes = CheckCollisionPointRec(mousePos, rYes);
    if (DrawMenuButton(rYes, yesText, hYes, (Color){60, 30, 30, 240}, (Color){110, 40, 40, 255})) {
        return 1; // YES clicked
    }

    // NO Button
    Rectangle rNo = {screenWidth/2.0f + 20, btnY, btnW, btnH};
    bool hNo = CheckCollisionPointRec(mousePos, rNo);
    if (DrawMenuButton(rNo, noText, hNo, (Color){30, 60, 30, 240}, (Color){40, 110, 40, 255})) {
        return 2; // NO clicked
    }

    return 0; // Nothing clicked
}

void DrawSuitSymbol(Vector2 center, float radius, Suit suit, Color color) {
    Vector2 c = center;
    switch (suit) {
        case SUIT_HEARTS: {
            float r = radius * 0.55f;
            Vector2 leftCircle = { c.x - r * 0.75f, c.y - r * 0.35f };
            Vector2 rightCircle = { c.x + r * 0.75f, c.y - r * 0.35f };
            DrawCircleV(leftCircle, r, color);
            DrawCircleV(rightCircle, r, color);
            Vector2 p1 = { c.x - r * 1.55f, c.y - r * 0.1f };
            Vector2 p2 = { c.x + r * 1.55f, c.y - r * 0.1f };
            Vector2 p3 = { c.x, c.y + radius * 1.05f };
            DrawTriangle(p1, p3, p2, color);
            break;
        }
        case SUIT_DIAMONDS: {
            Vector2 top = { c.x, c.y - radius * 1.15f };
            Vector2 bottom = { c.x, c.y + radius * 1.15f };
            Vector2 left = { c.x - radius * 0.85f, c.y };
            Vector2 right = { c.x + radius * 0.85f, c.y };
            DrawTriangle(left, right, top, color);
            DrawTriangle(left, bottom, right, color);
            break;
        }
        case SUIT_CLUBS: {
            float r = radius * 0.48f;
            Vector2 topC = { c.x, c.y - r * 0.85f };
            Vector2 leftC = { c.x - r * 0.85f, c.y + r * 0.35f };
            Vector2 rightC = { c.x + r * 0.85f, c.y + r * 0.35f };
            DrawCircleV(topC, r, color);
            DrawCircleV(leftC, r, color);
            DrawCircleV(rightC, r, color);
            Vector2 stemTop = { c.x, c.y };
            Vector2 stemBL = { c.x - r * 0.6f, c.y + radius * 1.1f };
            Vector2 stemBR = { c.x + r * 0.6f, c.y + radius * 1.1f };
            DrawTriangle(stemTop, stemBL, stemBR, color);
            break;
        }
        case SUIT_SPADES: {
            float r = radius * 0.55f;
            Vector2 leftCircle = { c.x - r * 0.75f, c.y + r * 0.35f };
            Vector2 rightCircle = { c.x + r * 0.75f, c.y + r * 0.35f };
            DrawCircleV(leftCircle, r, color);
            DrawCircleV(rightCircle, r, color);
            Vector2 p1 = { c.x - r * 1.5f, c.y + r * 0.2f };
            Vector2 p2 = { c.x + r * 1.5f, c.y + r * 0.2f };
            Vector2 p3 = { c.x, c.y - radius * 1.1f };
            DrawTriangle(p1, p2, p3, color);
            Vector2 stemTop = { c.x, c.y + r * 0.3f };
            Vector2 stemBL = { c.x - r * 0.6f, c.y + radius * 1.2f };
            Vector2 stemBR = { c.x + r * 0.6f, c.y + radius * 1.2f };
            DrawTriangle(stemTop, stemBL, stemBR, color);
            break;
        }
    }
}

void DrawCard(Card card, Rectangle rect, bool is_face_up) {
    // Drop Shadow
    Rectangle shadow = {rect.x + 10, rect.y + 10, rect.width, rect.height};
    DrawRectangleRounded(shadow, 0.08f, 10, (Color){0, 0, 0, 75});

    if (is_face_up) {
        // Crisp White Card Body
        DrawRectangleRounded(rect, 0.08f, 10, (Color){252, 252, 250, 255});
        DrawRectangleRoundedLines(rect, 0.08f, 10, (Color){40, 40, 40, 255});
        
        // Inner Decorative Frame
        Rectangle inner = {rect.x + 4, rect.y + 4, rect.width - 8, rect.height - 8};
        DrawRectangleRoundedLines(inner, 0.07f, 8, (Color){220, 215, 200, 255});

        Color suitColor = (card.suit == SUIT_HEARTS || card.suit == SUIT_DIAMONDS) ? (Color){200, 25, 25, 255} : (Color){25, 25, 25, 255};

        const char* rankStr = "6";
        switch (card.rank) {
            case RANK_6: rankStr = "6"; break;
            case RANK_7: rankStr = "7"; break;
            case RANK_8: rankStr = "8"; break;
            case RANK_9: rankStr = "9"; break;
            case RANK_10: rankStr = "10"; break;
            case RANK_J: rankStr = "В"; break;
            case RANK_Q: rankStr = "Д"; break;
            case RANK_K: rankStr = "К"; break;
            case RANK_A: rankStr = "Т"; break;
            default: break;
        }

        // Top-Left Index
        float indexFontSize = rect.width * 0.24f;
        DrawAppText(rankStr, rect.x + 7, rect.y + 6, indexFontSize, suitColor);
        DrawSuitSymbol((Vector2){rect.x + 14, rect.y + 38}, rect.width * 0.095f, card.suit, suitColor);

        // Bottom-Right Index (Mirrored)
        Vector2 brSize = MeasureAppText(rankStr, indexFontSize);
        DrawAppText(rankStr, rect.x + rect.width - brSize.x - 7, rect.y + rect.height - brSize.y - 6, indexFontSize, suitColor);
        DrawSuitSymbol((Vector2){rect.x + rect.width - 14, rect.y + rect.height - 38}, rect.width * 0.095f, card.suit, suitColor);

        // Center Artwork & Badges
        Vector2 center = {rect.x + rect.width / 2.0f, rect.y + rect.height / 2.0f};

        if (card.rank == RANK_A) {
            // Ace: Large Center Suit Symbol + Ornate Gold Ring
            DrawCircleLines(center.x, center.y, rect.width * 0.28f, GOLD);
            DrawSuitSymbol(center, rect.width * 0.24f, card.suit, suitColor);
        } else if (card.rank == RANK_K) {
            // King: Crown Emblem + Center Suit Symbol
            Vector2 cp1 = {center.x - 15, center.y - 12};
            Vector2 cp2 = {center.x + 15, center.y - 12};
            Vector2 cp3 = {center.x, center.y - 26};
            DrawTriangle(cp1, cp3, cp2, GOLD);
            DrawSuitSymbol(center, rect.width * 0.18f, card.suit, suitColor);
        } else if (card.rank == RANK_Q) {
            // Queen: Tiara Emblem + Center Suit Symbol
            DrawCircleLines(center.x, center.y - 15, 11, GOLD);
            DrawSuitSymbol(center, rect.width * 0.18f, card.suit, suitColor);
        } else if (card.rank == RANK_J) {
            // Jack: Shield Crest + Center Suit Symbol
            Rectangle shield = {center.x - 11, center.y - 22, 22, 18};
            DrawRectangleRoundedLines(shield, 0.2f, 4, DARKGRAY);
            DrawSuitSymbol(center, rect.width * 0.18f, card.suit, suitColor);
        } else {
            // Number Cards (6..10): Large Center Suit Symbol
            DrawSuitSymbol(center, rect.width * 0.20f, card.suit, suitColor);
        }
    } else {
        // Advanced Card Back
        DrawRectangleRounded(rect, 0.08f, 10, (Color){20, 45, 95, 255});
        DrawRectangleRoundedLines(rect, 0.08f, 10, WHITE);
        
        Rectangle inner = {rect.x + 6, rect.y + 6, rect.width - 12, rect.height - 12};
        DrawRectangleRoundedLines(inner, 0.08f, 10, SKYBLUE);

        Vector2 center = {rect.x + rect.width / 2.0f, rect.y + rect.height / 2.0f};
        DrawCircleLines(center.x, center.y, rect.width * 0.25f, GOLD);
        DrawCircleLines(center.x, center.y, rect.width * 0.18f, SKYBLUE);
    }
}

void DrawCardHighlight(Rectangle rect, Color color) {
    Rectangle highlight = {rect.x - 4, rect.y - 4, rect.width + 8, rect.height + 8};
    DrawRectangleRoundedLines(highlight, 0.1f, 10, color);
}

void DrawCardHintBadge(Vector2 topCenterPos, const char* text, Color color) {
    float fontSize = 19.0f;
    Vector2 sz = MeasureAppText(text, fontSize);
    float padX = 8.0f, padY = 4.0f;
    float boxW = sz.x + padX * 2;
    float boxH = sz.y + padY * 2;
    Rectangle r = {topCenterPos.x - boxW / 2.0f, topCenterPos.y - boxH - 6.0f, boxW, boxH};
    
    // Drop shadow
    DrawRectangleRounded((Rectangle){r.x + 2, r.y + 2, r.width, r.height}, 0.35f, 6, (Color){0, 0, 0, 140});
    // Badge Background & Outline
    DrawRectangleRounded(r, 0.35f, 6, (Color){20, 20, 20, 240});
    DrawRectangleRoundedLines(r, 0.35f, 6, color);
    
    // Pointer triangle
    Vector2 p1 = {topCenterPos.x - 4, r.y + boxH};
    Vector2 p2 = {topCenterPos.x + 4, r.y + boxH};
    Vector2 p3 = {topCenterPos.x, r.y + boxH + 4};
    DrawTriangle(p1, p3, p2, color);

    DrawAppText(text, r.x + padX, r.y + padY, fontSize, color);
}

void DrawKing(Rectangle rect, bool is_looking_away, KingState state) {
    if (!g_king_sprites_loaded) return;

    // Select the right texture based on current state.
    // Explicit emotions (angry/overwhelmed) take priority over the turned-away pose;
    // the turned sprite applies only to the neutral idle state.
    Texture2D tex;
    if (state == KING_STATE_IDLE && is_looking_away && g_king_sprites_loaded && g_king_turned.id > 0) {
        tex = g_king_turned;
    } else {
        switch (state) {
            case KING_STATE_ANGRY:       tex = g_king_angry;       break;
            case KING_STATE_OVERWHELMED: tex = g_king_overwhelmed; break;
            default:                     tex = g_king_idle;        break;
        }
    }

    // Scale the sprite to fit rect while preserving aspect ratio (letterbox/pillarbox)
    float srcW = (float)tex.width;
    float srcH = (float)tex.height;
    float scaleX = rect.width  / srcW;
    float scaleY = rect.height / srcH;
    float scale  = (scaleX < scaleY) ? scaleX : scaleY;
float characterScale = 4.0f;
scale *= characterScale;
    float dstW = srcW * scale;
    float dstH = srcH * scale;
    float dstX = rect.x + (rect.width  - dstW) * 0.5f;
    float dstY = rect.y + (rect.height - dstH) * 0.5f;

    Rectangle srcRect = { 0, 0, srcW, srcH };
    Rectangle dstRect = { dstX, dstY, dstW, dstH };
    DrawTexturePro(tex, srcRect, dstRect, (Vector2){0, 0}, 0.0f, WHITE);
}

void DrawKingTinted(Rectangle rect, bool is_looking_away, KingState state, Color tint) {
    if (!g_king_sprites_loaded) return;
    Texture2D tex;
    if (state == KING_STATE_IDLE && is_looking_away && g_king_sprites_loaded && g_king_turned.id > 0) {
        tex = g_king_turned;
    } else {
        switch (state) {
            case KING_STATE_ANGRY:       tex = g_king_angry;       break;
            case KING_STATE_OVERWHELMED: tex = g_king_overwhelmed; break;
            default:                     tex = g_king_idle;        break;
        }
    }
    float srcW = (float)tex.width;
    float srcH = (float)tex.height;
    float scaleX = rect.width  / srcW;
    float scaleY = rect.height / srcH;
    float scale  = (scaleX < scaleY) ? scaleX : scaleY;
    float characterScale = 4.0f;
    scale *= characterScale;
    float dstW = srcW * scale;
    float dstH = srcH * scale;
    float dstX = rect.x + (rect.width  - dstW) * 0.5f;
    float dstY = rect.y + (rect.height - dstH) * 0.5f;
    Rectangle srcRect = { 0, 0, srcW, srcH };
    Rectangle dstRect = { dstX, dstY, dstW, dstH };
    DrawTexturePro(tex, srcRect, dstRect, (Vector2){0, 0}, 0.0f, tint);
}

void DrawSpeechBubble(Vector2 pos, const char* text, float timer) {
    if (timer <= 0 || strlen(text) == 0) return;

    float fontSize = 22;
    Vector2 textSize = MeasureAppText(text, fontSize);
    float padX = 18.0f, padY = 12.0f;
    float boxW = textSize.x + padX * 2;
    float boxH = textSize.y + padY * 2;

    Rectangle bubble = {pos.x, pos.y - boxH / 2.0f, boxW, boxH};
    Rectangle bSh = {bubble.x + 3, bubble.y + 4, boxW, boxH};
    DrawRectangleRounded(bSh, 0.2f, 10, (Color){0, 0, 0, 110});
    DrawRectangleRounded(bubble, 0.2f, 10, (Color){255, 255, 240, 248});
    DrawRectangleRoundedLines(bubble, 0.2f, 10, GOLD);
    Rectangle bInner = {bubble.x + 3, bubble.y + 3, boxW - 6, boxH - 6};
    DrawRectangleRoundedLines(bInner, 0.2f, 10, Fade(GOLD, 0.40f));

    Vector2 p1 = {pos.x, pos.y - 5};
    Vector2 p2 = {pos.x, pos.y + 5};
    Vector2 p3 = {pos.x - 12, pos.y};
    DrawTriangle(p1, p3, p2, (Color){255, 255, 240, 248});

    DrawAppText(text, bubble.x + padX, bubble.y + padY, fontSize, BLACK);
}

void DrawMenuBackground(int screenWidth, int screenHeight) {
    // Deep royal velvet: vertical gradient emerald -> near-black
    DrawRectangleGradientV(0, 0, screenWidth, screenHeight,
                           (Color){ 24, 52, 40, 255 }, (Color){ 7, 15, 12, 255 });

    // Warm radial glow behind the title area (layered soft circles)
    float cx = screenWidth * 0.5f;
    float cy = screenHeight * 0.34f;
    float pulse = 6.0f + 7.0f * sinf(GetTime() * 1.1f);
    for (int i = 8; i >= 1; i--) {
        float r = (screenHeight * 0.16f + i * screenHeight * 0.075f) + pulse;
        unsigned char a = (unsigned char)(5 + i * 2);
        DrawCircleV((Vector2){ cx, cy }, r, (Color){ 210, 170, 90, a });
    }

    // Faint diamond lattice
    float cell = 46.0f;
    Color lattice = { 190, 155, 95, 9 };
    for (float x = -screenHeight; x < screenWidth; x += cell) {
        DrawLineEx((Vector2){ x, 0 }, (Vector2){ x + screenHeight, screenHeight }, 1.0f, lattice);
        DrawLineEx((Vector2){ x, 0 }, (Vector2){ x - screenHeight, screenHeight }, 1.0f, lattice);
    }

    // Oversized faded suit symbols in the corners
    Color suits = { 200, 165, 100, 14 };
    DrawSuitSymbol((Vector2){ -30.0f, -20.0f }, 70.0f, SUIT_HEARTS, suits);
    DrawSuitSymbol((Vector2){ screenWidth + 30.0f, -20.0f }, 70.0f, SUIT_SPADES, suits);
    DrawSuitSymbol((Vector2){ -30.0f, screenHeight + 20.0f }, 70.0f, SUIT_CLUBS, suits);
    DrawSuitSymbol((Vector2){ screenWidth + 30.0f, screenHeight + 20.0f }, 70.0f, SUIT_DIAMONDS, suits);

    // Ornate double frame with corner diamonds
    Rectangle f1 = { 10.0f, 10.0f, screenWidth - 20.0f, screenHeight - 20.0f };
    DrawRectangleRoundedLines(f1, 0.02f, 8, Fade(GOLD, 0.55f));
    Rectangle f2 = { 16.0f, 16.0f, screenWidth - 32.0f, screenHeight - 32.0f };
    DrawRectangleRoundedLines(f2, 0.03f, 8, Fade(GOLD, 0.22f));
    {
        float m = 13.0f;
        Vector2 corners[4] = {
            { m, m },
            { screenWidth - m, m },
            { m, screenHeight - m },
            { screenWidth - m, screenHeight - m }
        };
        for (int i = 0; i < 4; i++) {
            DrawDiamond(corners[i], 4.0f, GOLD);
            DrawDiamond(corners[i], 1.8f, (Color){ 255, 240, 200, 255 });
        }
    }

    // Cinematic vignette
    int vg = screenHeight / 5 > 140 ? 140 : screenHeight / 5;
    DrawRectangleGradientH(0, 0, vg, screenHeight, (Color){0, 0, 0, 60}, (Color){0, 0, 0, 0});
    DrawRectangleGradientH(screenWidth - vg, 0, vg, screenHeight, (Color){0, 0, 0, 0}, (Color){0, 0, 0, 60});
    int vgy = screenWidth / 6 > 120 ? 120 : screenWidth / 6;
    DrawRectangleGradientV(0, 0, screenWidth, vgy, (Color){0, 0, 0, 55}, (Color){0, 0, 0, 0});
    DrawRectangleGradientV(0, screenHeight - vgy, screenWidth, vgy, (Color){0, 0, 0, 0}, (Color){0, 0, 0, 55});
}

void DrawHintBanner(float centerX, float y, const char* text, Color accent) {
    if (!text || text[0] == '\0') return;

    float fontSize = 24.0f;
    Vector2 sz = MeasureAppText(text, fontSize);
    float padX = 22.0f, padY = 12.0f;
    float boxW = sz.x + padX * 2;
    float boxH = sz.y + padY * 2;

    Rectangle r = { centerX - boxW / 2.0f, y, boxW, boxH };
    Rectangle sh = { r.x + 3, r.y + 5, boxW, boxH };

    DrawRectangleRounded(sh, 0.30f, 8, (Color){0, 0, 0, 150});
    DrawRectangleRounded(r, 0.30f, 8, (Color){16, 13, 9, 242});

    float pulse = 0.55f + 0.45f * sinf(GetTime() * 4.5f);
    Rectangle glow = { r.x - 3, r.y - 3, boxW + 6, boxH + 6 };
    DrawRectangleRoundedLines(glow, 0.28f, 8, Fade(accent, 0.35f * pulse));
    DrawRectangleRoundedLines(r, 0.30f, 8, Fade(accent, 0.45f + 0.55f * pulse));
    Rectangle inner = { r.x + 3, r.y + 3, boxW - 6, boxH - 6 };
    DrawRectangleRoundedLines(inner, 0.30f, 8, Fade(accent, 0.25f));

    float cy = r.y + boxH / 2.0f;
    float dx = boxW / 2.0f - 10.0f;
    Color bright = ScaleColor(accent, 1.4f);
    DrawDiamond((Vector2){r.x + dx, cy}, 3.5f, bright);
    DrawDiamond((Vector2){r.x + boxW - dx, cy}, 3.5f, bright);

    DrawAppText(text, r.x + padX + 1.5f, r.y + padY + 2.0f, fontSize, (Color){0, 0, 0, 180});
    DrawAppText(text, r.x + padX, r.y + padY, fontSize, bright);
}

void DrawTableTexture(int screenWidth, int screenHeight) {
    if (g_table_loaded) {
        // Stretch the table sprite to fill the entire canvas, preserving aspect ratio with cover-fit
        float texW = (float)g_table_texture.width;
        float texH = (float)g_table_texture.height;
        float scaleX = screenWidth  / texW;
        float scaleY = screenHeight / texH;
        // Use the larger scale so the image always covers the full background (cover fit)
        float s = scaleX > scaleY ? scaleX : scaleY;
        float drawW = texW * s;
        float drawH = texH * s;
        float ox = (screenWidth  - drawW) * 0.5f;
        float oy = (screenHeight - drawH) * 0.5f;
        Rectangle src = { 0, 0, texW, texH };
        Rectangle dst = { ox, oy, drawW, drawH };
        DrawTexturePro(g_table_texture, src, dst, (Vector2){0, 0}, 0.0f, WHITE);
    } else {
        // Fallback if sprite not loaded
        DrawRectangleGradientV(0, 0, screenWidth, screenHeight, (Color){28, 62, 42, 255}, (Color){14, 34, 22, 255});
        DrawRectangleLines(10, 10, screenWidth - 20, screenHeight - 20, (Color){85, 60, 30, 120});
        DrawRectangleLines(14, 14, screenWidth - 28, screenHeight - 28, (Color){180, 140, 70, 70});
    }

    // Cinematic vignette: darken edges so UI panels pop
    int vg = screenHeight / 5 > 140 ? 140 : screenHeight / 5;
    DrawRectangleGradientH(0, 0, vg, screenHeight, (Color){0, 0, 0, 60}, (Color){0, 0, 0, 0});
    DrawRectangleGradientH(screenWidth - vg, 0, vg, screenHeight, (Color){0, 0, 0, 0}, (Color){0, 0, 0, 60});
    int vgy = screenWidth / 6 > 120 ? 120 : screenWidth / 6;
    DrawRectangleGradientV(0, 0, screenWidth, vgy, (Color){0, 0, 0, 55}, (Color){0, 0, 0, 0});
    DrawRectangleGradientV(0, screenHeight - vgy, screenWidth, vgy, (Color){0, 0, 0, 0}, (Color){0, 0, 0, 55});
}

void DrawCheatingProgress(Vector2 pos, float progress) {
    if (progress > 1.0f) progress = 1.0f;
    float width = 140;
    float height = 14;
    DrawRectangle(pos.x, pos.y, width, height, (Color){20, 20, 20, 200});
    DrawRectangle(pos.x + 2, pos.y + 2, (width - 4) * progress, height - 4, GOLD);
    DrawRectangleLines(pos.x, pos.y, width, height, WHITE);
}

void DrawReachingArm(Vector2 startPos, Vector2 deckPos, float progress) {
    if (progress <= 0) return;
    if (progress > 1.0f) progress = 1.0f;

    Vector2 handPos;
    if (progress < 0.5f) {
        float t = progress / 0.5f;
        handPos = (Vector2){
            startPos.x + (deckPos.x - startPos.x) * t,
            startPos.y + (deckPos.y - startPos.y) * t - 30.0f * (1.0f - (2.0f * t - 1.0f) * (2.0f * t - 1.0f))
        };
    } else {
        float t = (progress - 0.5f) / 0.5f;
        handPos = (Vector2){
            deckPos.x + (startPos.x - deckPos.x) * t,
            deckPos.y + (startPos.y - deckPos.y) * t - 30.0f * (1.0f - (2.0f * t - 1.0f) * (2.0f * t - 1.0f))
        };
    }

    Vector2 elbow = {
        (startPos.x + handPos.x) / 2.0f - 20.0f,
        (startPos.y + handPos.y) / 2.0f + 25.0f
    };

    // Sleeve
    DrawLineEx(startPos, elbow, 16.0f, (Color){35, 25, 45, 255});
    DrawLineEx(elbow, handPos, 14.0f, (Color){45, 35, 55, 255});
    DrawCircleV(elbow, 9.0f, (Color){35, 25, 45, 255});

    // Gold Cuff
    DrawCircleV(handPos, 8.0f, GOLD);

    // Grasping Hand
    DrawCircleV(handPos, 7.0f, (Color){240, 200, 160, 255});
    DrawCircleV((Vector2){handPos.x - 3, handPos.y - 4}, 3.0f, (Color){230, 190, 150, 255});
    DrawCircleV((Vector2){handPos.x + 3, handPos.y - 4}, 3.0f, (Color){230, 190, 150, 255});
}

void DrawSwapNotification(Vector2 pos, Card oldCard, Card newCard, float timer, Language lang) {
    if (timer <= 0) return;

    const char* title = GetUIText("SWAP_NOTICE_TITLE", lang);

    float boxW = 330, boxH = 172;
    Rectangle box = {pos.x - boxW/2.0f, pos.y - boxH/2.0f, boxW, boxH};

    DrawRoyalPanel(box, ROYAL_GOLD);

    Vector2 titleSz = MeasureAppText(title, 21);
    DrawAppText(title, pos.x - titleSz.x/2.0f, box.y + 9, 21, GOLD);

    // Mini cards dimensions: 74x109
    float miniW = 74, miniH = 109;
    Rectangle rOld = {box.x + 26, box.y + 46, miniW, miniH};
    Rectangle rNew = {box.x + boxW - miniW - 26, box.y + 46, miniW, miniH};

    DrawCard(oldCard, rOld, true);

    // Short compact arrow between the cards
    {
        float cy = box.y + 46.0f + miniH / 2.0f;
        float cx = pos.x;
        float shaftL = cx - 19.0f;
        float headBase = cx - 7.0f;
        DrawLineEx((Vector2){ shaftL, cy }, (Vector2){ headBase, cy }, 5.0f, GOLD);
        Vector2 tip  = { cx + 15.0f, cy };
        Vector2 up   = { headBase, cy - 9.0f };
        Vector2 down = { headBase, cy + 9.0f };
        DrawTriangle(up, down, tip, GOLD);
    }

    DrawCard(newCard, rNew, true);
}
